version: 2

sources:
  - name: raw
    schema: DBT_data08262
    description: raw data for cc parcel tracking
    tables:
      - name: parcel
        identifier: raw_cc_parcel
        description: details of each parcel for an order
        columns:
          - name: ParCEL_id
            description: unique id of the parcel
            tests:
              - unique
              - not_null
          - name: Date_purCHase
            description: purchase date of the order
            tests:
              - not_null
              
              
              

  
#  - name: iyzico

#  - name: typeform

#  - name: nextgen

#  - name: sendgrid